"""Registry of all checks performed by Polaris, used by `polaris checks`."""

CHECKS = {
    "security": {
        "name": "Security",
        "checks": [
            {"id": "https", "name": "HTTPS usage", "description": "Verifies the site uses HTTPS"},
            {"id": "https_redirect", "name": "HTTP to HTTPS redirect", "description": "Checks that HTTP requests redirect to HTTPS"},
            {"id": "ssl_cert", "name": "SSL certificate", "description": "Validates certificate expiry, TLS version, and chain"},
            {"id": "hsts", "name": "Strict-Transport-Security", "description": "Checks for HSTS header with appropriate max-age"},
            {"id": "csp", "name": "Content-Security-Policy", "description": "Checks for CSP header to prevent XSS and injection"},
            {"id": "x_frame", "name": "X-Frame-Options", "description": "Checks for clickjacking protection header"},
            {"id": "x_content_type", "name": "X-Content-Type-Options", "description": "Checks for nosniff header to prevent MIME sniffing"},
            {"id": "referrer", "name": "Referrer-Policy", "description": "Checks for referrer policy to control information leakage"},
            {"id": "permissions", "name": "Permissions-Policy", "description": "Checks for permissions policy restricting browser features"},
            {"id": "mixed_content", "name": "Mixed content", "description": "Finds HTTP resources loaded on HTTPS pages"},
            {"id": "form_security", "name": "Form security", "description": "Checks that forms submit sensitive data over HTTPS"},
            {"id": "cookie_flags", "name": "Cookie security flags", "description": "Validates Secure, HttpOnly, and SameSite attributes"},
        ],
    },
    "privacy": {
        "name": "Privacy & GDPR",
        "checks": [
            {"id": "cookie_consent", "name": "Cookie consent banner", "description": "Detects consent banner and CMP (Cookiebot, OneTrust, etc.)"},
            {"id": "pre_consent", "name": "Pre-consent cookies", "description": "Checks for non-essential cookies set before user consent"},
            {"id": "consent_buttons", "name": "Accept/reject options", "description": "Verifies both accept and reject buttons exist in consent UI"},
            {"id": "consent_granularity", "name": "Granular consent", "description": "Checks for per-category consent (analytics, marketing, etc.)"},
            {"id": "consent_withdrawal", "name": "Consent withdrawal", "description": "Checks that users can change or withdraw consent easily"},
            {"id": "pre_ticked", "name": "Pre-ticked boxes", "description": "Detects pre-checked consent checkboxes (GDPR violation)"},
            {"id": "cookie_policy", "name": "Cookie policy link", "description": "Checks for link to a cookie policy from the consent banner"},
            {"id": "privacy_policy", "name": "Privacy policy", "description": "Detects privacy policy link in footer/navigation (8 languages)"},
            {"id": "policy_content", "name": "Policy content", "description": "Validates required GDPR elements (retention, rights, basis, etc.)"},
            {"id": "third_party", "name": "Third-party services", "description": "Classifies 50+ services by consent tier (essential/analytics/marketing)"},
            {"id": "data_rights", "name": "Data subject rights", "description": "Checks for erasure, portability, rectification, access rights info"},
            {"id": "data_retention", "name": "Data retention", "description": "Checks for documented data retention periods"},
            {"id": "lawful_basis", "name": "Lawful basis", "description": "Checks for disclosure of legal basis for data processing"},
            {"id": "google_fonts", "name": "Google Fonts privacy", "description": "Flags Google Fonts loading without consent (IP sharing)"},
        ],
    },
    "accessibility": {
        "name": "Accessibility (WCAG)",
        "checks": [
            {"id": "page_title", "name": "Page title", "description": "Checks for a descriptive <title> element"},
            {"id": "lang_attr", "name": "Language attribute", "description": "Checks for lang attribute on <html> element"},
            {"id": "headings", "name": "Heading hierarchy", "description": "Validates H1-H6 structure (skipped levels, multiple H1s)"},
            {"id": "landmarks", "name": "Landmarks", "description": "Checks for <main>, <nav>, <header>, <footer> and ARIA roles"},
            {"id": "img_alt", "name": "Image alt text", "description": "Checks all <img> and <svg> elements for alt text / titles"},
            {"id": "form_labels", "name": "Form labels", "description": "Checks that inputs have associated <label> or aria-label"},
            {"id": "form_autocomplete", "name": "Form autocomplete", "description": "Checks for autocomplete attributes on form fields"},
            {"id": "form_errors", "name": "Form error handling", "description": "Checks for error message patterns and aria-describedby"},
            {"id": "video_captions", "name": "Video accessibility", "description": "Checks for captions/subtitles and controls on <video>"},
            {"id": "audio_transcript", "name": "Audio accessibility", "description": "Checks for controls and transcript links on <audio>"},
            {"id": "skip_links", "name": "Skip navigation", "description": "Checks for skip-to-content links"},
            {"id": "link_text", "name": "Link text quality", "description": "Flags empty, generic (\"click here\"), or ambiguous link text"},
            {"id": "keyboard_focus", "name": "Keyboard focus", "description": "Checks for visible focus indicators and tabindex usage"},
            {"id": "nav_structure", "name": "Navigation structure", "description": "Checks that <nav> uses proper <ul>/<li> list structure"},
            {"id": "tables", "name": "Table accessibility", "description": "Checks for <th>, scope attributes, and <caption>"},
            {"id": "color_only", "name": "Color-only indicators", "description": "Flags elements that rely only on color to convey meaning"},
            {"id": "color_contrast", "name": "Color contrast", "description": "Checks text/background contrast ratios"},
            {"id": "figures", "name": "Figure captions", "description": "Checks <figure> elements for <figcaption>"},
        ],
    },
    "performance": {
        "name": "Performance",
        "checks": [
            {"id": "compression", "name": "Compression", "description": "Checks for gzip/brotli content encoding on responses"},
            {"id": "caching", "name": "Caching headers", "description": "Validates Cache-Control, ETag, Last-Modified, Expires"},
            {"id": "image_format", "name": "Image optimization", "description": "Flags PNG/JPG without WebP/AVIF alternatives"},
            {"id": "js_blocking", "name": "Render-blocking JS", "description": "Counts scripts missing async/defer attributes"},
            {"id": "js_minified", "name": "JavaScript minification", "description": "Detects unminified JavaScript bundles"},
            {"id": "css_optimize", "name": "CSS optimization", "description": "Flags excess stylesheets, unminified CSS, large inline styles"},
            {"id": "page_weight", "name": "Page weight", "description": "Flags pages over 200KB/500KB/1MB"},
            {"id": "resource_hints", "name": "Resource hints", "description": "Checks for preload, prefetch, dns-prefetch on critical resources"},
        ],
    },
}
